// ps_black_white.metal -- mechanical port from ps_black_white.frag
// Generated by tools/glsl_to_msl/glsl_to_msl.py . Doctrine : pure Apple
// Metal, no SPIR-V / Vulkan IR (memory/feedback_nvidia_to_metal.md).
//
// Manual review required for any `// TODO_PORT:` marker below.

#include <metal_stdlib>
using namespace metal;

struct VertexOut
{
    float4 position [[position]];
    float2 uv;
};

//	---- inline engine MSL prelude (from aaa_prelude.mslh) ----
// src/shaders/msl/aaa_prelude.metal
//
// Mac-side MSL equivalent of the engine's per-frame GLSL prelude
// helpers. On Windows, `GLSL_shader.cpp` prepends `include_color.glsl`
// (and platform-specific siblings) to each shader at registration time
// so calls like `gray( c.rgb )` resolve at compile time. On Mac we
// follow the same pattern : `tools/glsl_to_msl/glsl_to_msl.py`
// inline-prepends this file's content to every emitted `.metal` so each
// generated shader is self-contained for `MTL::Device::newLibrary`.
//
// SOURCE OF TRUTH for the engine semantics :
//   vendor/aaaseed-runtime/AAAKernel/Shader/include/include_color.glsl
//
// Keep this file's gray_conv values byte-equivalent to the engine's so
// pixel-comparable output across Mac / Windows stays plausible.
// `gray_conv = vec3(0.2989, 0.5870, 0.1140)` are the standard NTSC
// luminance weights (Rec.601). Engine has used these since forever.
//
// Doctrine : pure Apple Metal -- this file is MSL, not GLSL.
// (memory/feedback_nvidia_to_metal.md / philosophy.md Part 2.86)
//
// NOT INCLUDED yet (port on demand as catalog shaders need them) :
//   - get_gradient_2d / get_gradient_norm_2d : need to pass texture +
//     sampler explicitly in MSL (no GLSL "in sampler2D" idiom).
//   - rgb2hsv / hsv2rgb : straightforward port, awaits a catalog
//     shader that needs them.

#ifndef AAA_MSL_PRELUDE_DEFINED
#define AAA_MSL_PRELUDE_DEFINED

//	Constant must match the engine include_color.glsl gray_conv. The
//	`constexpr constant` form is MSL's named-constant pattern.
constexpr constant float3 aaa_gray_conv = float3( 0.2989, 0.5870, 0.1140 );

//	Two names because the engine has two -- aliases of the same body.
//	Both have float3 and float4 overloads : engine shaders pass either
//	`gray( c.xyz )` (post-translation : float3) or `gray( c )` where c
//	is the full RGBA texture sample (float4). Continuation 33 added the
//	float4 overload for ps_Maa_edge_sobel.
static inline float gray( float3 a )
{
    return dot( a.xyz, aaa_gray_conv );
}

static inline float gray( float4 a )
{
    return dot( a.xyz, aaa_gray_conv );
}

static inline float compute_gray( float3 a )
{
    return dot( a.xyz, aaa_gray_conv );
}

static inline float compute_gray( float4 a )
{
    return dot( a.xyz, aaa_gray_conv );
}

#endif // AAA_MSL_PRELUDE_DEFINED


//	Engine convention : aaa_fu_float[N] / aaa_fu_vec4[N] / aaa_fu_int[N]
//	arrays uploaded per frame. Fixed-size structs match what the Windows
//	engine writes ; the runtime asset pipeline must produce the same
//	layout on Mac.
struct AaaFuFloats { float  values[ 16 ]; };
struct AaaFuVec4s  { float4 values[ 16 ]; };
struct AaaFuInts   { int    values[ 16 ]; };

// ---- helper functions (translated + mutated) ----



float3 bw1( texture2d< float > tex0, sampler _aaa_samp, float2 _aaa_uv )
{
float4	tex = tex0.sample(_aaa_samp, _aaa_uv.xy);

	tex *= 0.3333333333;

	float sat = tex.x + tex.y + tex.z;
	float3 color;
	if( sat >= .1 )
		color = float3( 1.0 );
	else
		color = float3( 0.0 );

	return color;

}



float3 bw2( texture2d< float > tex0, sampler _aaa_samp, float2 _aaa_uv, constant AaaFuFloats& _aaa_floats )
{
	float3 d2 = float3( _aaa_floats.values[0], -_aaa_floats.values[0], 0.0 );

	float4	tex = tex0.sample(_aaa_samp, _aaa_uv.xy);
	float4	texture_sum;
	texture_sum = tex0.sample(_aaa_samp, _aaa_uv.xy + d2.yz)
				+ tex0.sample(_aaa_samp, _aaa_uv.xy + d2.yx)
				+ tex0.sample(_aaa_samp, _aaa_uv.xy + d2.xy)
				+ tex0.sample(_aaa_samp, _aaa_uv.xy + d2.xz)
				+ tex0.sample(_aaa_samp, _aaa_uv.xy + d2.xx)
				+ tex0.sample(_aaa_samp, _aaa_uv.xy + d2.zy)
				+ tex0.sample(_aaa_samp, _aaa_uv.xy + d2.zx)
				+ tex0.sample(_aaa_samp, _aaa_uv.xy + d2.yy);
	texture_sum *= 0.125;



	float border;
	border = texture_sum.x + texture_sum.y + texture_sum.z;
	float actual;
	actual = tex.x + tex.y + tex.z;
	border *= 0.3333333;
	actual *= 0.3333333;




if( actual < .01 )
	actual = 1.0;
else
	actual = 0.0;

if( border >= .01 )
	border = 1.0;
else
	border = 0.0;

	float3 color;

	color = max( tex.xyz, float3( border * actual ) );
	return color;


}


//	Pass-through vertex stage. Oversized triangle covers the full screen ;
//	uv runs [0,1] over the visible quadrant.
vertex VertexOut vs_main( uint vid [[vertex_id]] )
{
    float2 verts[ 3 ] = { float2( -1.0, -3.0 ),
                          float2( -1.0,  1.0 ),
                          float2(  3.0,  1.0 ) };
    float2 uvs  [ 3 ] = { float2( 0.0, 2.0 ),
                          float2( 0.0, 0.0 ),
                          float2( 2.0, 0.0 ) };
    VertexOut out;
    out.position = float4( verts[ vid ], 0.0, 1.0 );
    out.uv       = uvs[ vid ];
    return out;
}

fragment float4 fs_main( VertexOut in [[stage_in]], texture2d< float > tex0 [[texture(0)]], sampler _aaa_samp [[sampler(0)]], constant AaaFuFloats& _aaa_floats [[buffer(0)]] )
{
    float4 _aaa_fragout = float4( 0.0 );
    
    	if( _aaa_floats.values[1] >= 1.0 )
    		_aaa_fragout.xyz = bw2( tex0, _aaa_samp, in.uv, _aaa_floats );
    	else
    		_aaa_fragout.xyz = bw1( tex0, _aaa_samp, in.uv );
    return _aaa_fragout;
}
