// shader_msl_port_test.cpp
//
// Path A hand-port verification : take the MSL produced by direct
// GLSL -> MSL hand-translation of `vendor/aaaseed-runtime/AAAKernel/Shader/
// ps_edgeoverlay.frag` and check that it :
//   1. compiles via `MTL::Device::newLibrary` (the raw Apple pipeline ;
//      proves AppleClang's Metal compiler accepts the MSL),
//   2. produces both `vs_main` and `fs_main` as non-null `MTL::Function`,
//   3. is accepted by `GOL::MetalBackend::create_program_msl` (the engine's
//      front door for MSL).
//
// The MSL is embedded as a `constexpr char const*` so the test is hermetic --
// no on-disk dependency, no filesystem walk, no copy step at build time.
// When the .metal file in `src/shaders/msl/` is updated the constant below
// must be regenerated by hand (acceptable for the first ported shader ; a
// CMake-based generator can come later).

#include <gtest/gtest.h>

#define NS_PRIVATE_IMPLEMENTATION_NO  // impl lives in aaaseed_gol_metal
#include <Foundation/Foundation.hpp>
#include <Metal/Metal.hpp>

#include "src/gol/gol_backend.h"
#include "src/gol/metal/metal_backend.h"

namespace
{
    //	Source of truth : `src/shaders/msl/ps_edgeoverlay.metal`. Kept in
    //	sync by hand. Any change to that file must be mirrored here ; the
    //	hermetic-test trade-off (no FS reads in the test runner) is worth the
    //	manual sync until we wire a baker. See the .metal file's top comment
    //	for the GLSL -> MSL port notes.
    constexpr char const* kPsEdgeOverlayMsl = R"MSL(
#include <metal_stdlib>
using namespace metal;

struct EdgeOverlayUniforms
{
    float fu[ 16 ];
};

struct VertexOut
{
    float4 position [[position]];
    float2 uv;
};

vertex VertexOut vs_main( uint vid [[vertex_id]] )
{
    float2 verts[ 3 ];
    verts[ 0 ] = float2( -1.0, -3.0 );
    verts[ 1 ] = float2( -1.0,  1.0 );
    verts[ 2 ] = float2(  3.0,  1.0 );

    float2 uvs[ 3 ];
    uvs[ 0 ] = float2( 0.0,  2.0 );
    uvs[ 1 ] = float2( 0.0,  0.0 );
    uvs[ 2 ] = float2( 2.0,  0.0 );

    VertexOut out;
    out.position = float4( verts[ vid ], 0.0, 1.0 );
    out.uv       = uvs[ vid ];
    return out;
}

constexpr constant float3 kGreyWeights = float3( 0.33333 );

static inline float get_gray( float4 c )
{
    return dot( c.rgb, kGreyWeights );
}

fragment float4 fs_main( VertexOut in                                [[stage_in]],
                         texture2d< float >          aaa_tex2d_0     [[texture(0)]],
                         sampler                     aaa_samp_0      [[sampler(0)]],
                         constant EdgeOverlayUniforms& U             [[buffer(0)]] )
{
    float NPixels   = U.fu[ 0 ];
    float Threshold = U.fu[ 1 ] * U.fu[ 1 ];

    float tex_sx = float( aaa_tex2d_0.get_width()  );
    float tex_sy = float( aaa_tex2d_0.get_height() );
    float delta_x = NPixels / tex_sx;
    float delta_y = NPixels / tex_sy;

    float2 uv = in.uv;

    float4 tmp;
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2( -delta_x, -delta_y ) );
    float g00 = get_gray( tmp );
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2(      0.0, -delta_y ) );
    float g01 = get_gray( tmp );
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2(  delta_x, -delta_y ) );
    float g02 = get_gray( tmp );
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2( -delta_x,      0.0 ) );
    float g10 = get_gray( tmp );
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2(  delta_x,      0.0 ) );
    float g12 = get_gray( tmp );
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2( -delta_x,  delta_y ) );
    float g20 = get_gray( tmp );
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2(      0.0,  delta_y ) );
    float g21 = get_gray( tmp );
    tmp = aaa_tex2d_0.sample( aaa_samp_0, uv + float2(  delta_x,  delta_y ) );
    float g22 = get_gray( tmp );

    float sx = g22 + 2.0 * g21 + g20 - g02 - g01 * 2.0 - g00;
    float sy = g22 -       g20 + g12 * 2.0 - 2.0 * g10 + g02 - g00;

    float dist = sx * sx + sy * sy;

    if( dist > Threshold )
    {
        discard_fragment();
    }

    float alpha;
    if( dist > ( Threshold * 0.5 ) )
        alpha = 1.0 - smoothstep( Threshold * 0.5, Threshold, dist );
    else
        alpha = 1.0;

    float4 color;
    color.rgb = aaa_tex2d_0.sample( aaa_samp_0, uv ).rgb;
    color.a   = alpha;

    return color;
}
)MSL";
}

//	Test 1 : raw Apple Metal compiler accepts the hand-ported MSL.
//	Mirrors the lowest-level path : `MTL::Device::newLibrary( NS::String*,
//	MTL::CompileOptions*, NS::Error** )`. If this fails, the MSL has a
//	syntax / semantic error that the engine layer can't paper over.
TEST( ShaderMslPort, PsEdgeOverlay_NewLibraryAcceptsMsl )
{
    MTL::Device* device = MTL::CreateSystemDefaultDevice();
    ASSERT_NE( device, nullptr ) << "no Metal-capable device on this host";

    NS::String* src = NS::String::string( kPsEdgeOverlayMsl, NS::UTF8StringEncoding );
    ASSERT_NE( src, nullptr );

    NS::Error*    err = nullptr;
    MTL::Library* lib = device->newLibrary( src, /*options*/ nullptr, &err );

    //	If compile failed, surface the Metal-compiler diagnostic in the
    //	gtest failure message so the porter sees the actual error line.
    if( !lib )
    {
        std::string desc = "newLibrary returned nullptr (no NS::Error)";
        if( err && err->localizedDescription() )
            desc = err->localizedDescription()->utf8String();
        FAIL() << "Metal compile failed : " << desc;
    }

    //	Both entry points must resolve to real MTL::Function objects.
    NS::String* vs_name = NS::String::string( "vs_main", NS::UTF8StringEncoding );
    NS::String* fs_name = NS::String::string( "fs_main", NS::UTF8StringEncoding );

    MTL::Function* vs = lib->newFunction( vs_name );
    MTL::Function* fs = lib->newFunction( fs_name );

    EXPECT_NE( vs, nullptr ) << "`vs_main` not found in compiled MSL library";
    EXPECT_NE( fs, nullptr ) << "`fs_main` not found in compiled MSL library";

    if( vs ) vs->release();
    if( fs ) fs->release();
    lib->release();
    device->release();
}

//	Test 2 : the engine's GOL::MetalBackend front door accepts the MSL.
//	This is the integration path real engine code will use ; mirrors what
//	`AAASeedMTKView.mm` does with the inline triangle shader.
TEST( ShaderMslPort, PsEdgeOverlay_MetalBackendBuildsProgram )
{
    GOL::MetalBackend backend;
    ASSERT_TRUE( backend.init() ) << "MetalBackend init failed";

    GOL::ProgramId prog = backend.create_program_msl(
        kPsEdgeOverlayMsl,
        "vs_main",
        "fs_main" );

    ASSERT_NE( prog, GOL::kInvalidProgramId )
        << "MetalBackend rejected hand-ported MSL : "
        << backend.get_last_error();

    backend.delete_program( prog );
}

//	Test 3 : second hand-ported shader (continuation 28). MSL embedded
//	from src/shaders/msl/ps_Maa_add_scale.metal . Engine semantic :
//	output = offset + tex_sample * scale, both per-channel float4s
//	delivered through a constant buffer at slot 0.
//	Source of truth : src/shaders/msl/ps_Maa_add_scale.metal . Manual
//	sync ; if the .metal file changes, the constant below regenerates by
//	hand. When the mechanical-substitution tool (Group B item) lands,
//	this duplication goes away.
constexpr char const* kPsMaaAddScaleMsl = R"MSL(
#include <metal_stdlib>
using namespace metal;

struct VertexOut
{
    float4 position [[position]];
    float2 uv;
};

struct AddScaleUniforms
{
    float4 offset;
    float4 scale;
};

vertex VertexOut vs_main( uint vid [[vertex_id]] )
{
    float2 verts[ 3 ] = { float2( -1.0, -3.0 ),
                          float2( -1.0,  1.0 ),
                          float2(  3.0,  1.0 ) };
    float2 uvs  [ 3 ] = { float2( 0.0, 2.0 ),
                          float2( 0.0, 0.0 ),
                          float2( 2.0, 0.0 ) };
    VertexOut out;
    out.position = float4( verts[ vid ], 0.0, 1.0 );
    out.uv       = uvs[ vid ];
    return out;
}

fragment float4 fs_main( VertexOut                       in   [[stage_in]],
                         texture2d< float >              tex  [[texture(0)]],
                         sampler                         samp [[sampler(0)]],
                         constant AddScaleUniforms&      U    [[buffer(0)]] )
{
    float4 const src = tex.sample( samp, in.uv );
    return U.offset + src * U.scale;
}
)MSL";

TEST( ShaderMslPort, PsMaaAddScale_NewLibraryAcceptsMsl )
{
    MTL::Device* device = MTL::CreateSystemDefaultDevice();
    ASSERT_NE( device, nullptr );

    NS::String*   msl_ns = NS::String::string( kPsMaaAddScaleMsl,
                                               NS::StringEncoding::UTF8StringEncoding );
    NS::Error*    err    = nullptr;
    MTL::Library* lib    = device->newLibrary( msl_ns, nullptr, &err );

    ASSERT_NE( lib, nullptr )
        << "newLibrary failed : "
        << ( err && err->localizedDescription() ? err->localizedDescription()->utf8String() : "(no error obj)" )
        << "\n--- MSL ---\n" << kPsMaaAddScaleMsl;

    NS::String* vs_name = NS::String::string( "vs_main",
                                              NS::StringEncoding::UTF8StringEncoding );
    NS::String* fs_name = NS::String::string( "fs_main",
                                              NS::StringEncoding::UTF8StringEncoding );
    MTL::Function* vs = lib->newFunction( vs_name );
    MTL::Function* fs = lib->newFunction( fs_name );
    EXPECT_NE( vs, nullptr );
    EXPECT_NE( fs, nullptr );

    if( vs ) vs->release();
    if( fs ) fs->release();
    lib->release();
    device->release();
}

TEST( ShaderMslPort, PsMaaAddScale_MetalBackendBuildsProgram )
{
    GOL::MetalBackend backend;
    ASSERT_TRUE( backend.init() );

    GOL::ProgramId prog = backend.create_program_msl(
        kPsMaaAddScaleMsl,
        "vs_main",
        "fs_main" );

    ASSERT_NE( prog, GOL::kInvalidProgramId )
        << "MetalBackend rejected ps_Maa_add_scale MSL : "
        << backend.get_last_error();

    backend.delete_program( prog );
}

//	Test 4 (continuation 29) : a TOOL-generated MSL port. Source GLSL
//	was hand-fed through tools/glsl_to_msl/glsl_to_msl.py and the result
//	embedded here. If Apple's Metal compiler accepts the tool's output,
//	the mechanical-substitution path is real (not just hand-port +
//	hopeful regex). When more shaders get tool-ported, each gets a test
//	in this file's pattern. CTest label still `integration` ;
//	`shader_msl_port` for the discriminator.
constexpr char const* kPsMaa4texMsl = R"MSL(
#include <metal_stdlib>
using namespace metal;

struct VertexOut
{
    float4 position [[position]];
    float2 uv;
};

struct AaaFuFloats { float  values[ 16 ]; };
struct AaaFuVec4s  { float4 values[ 16 ]; };

vertex VertexOut vs_main( uint vid [[vertex_id]] )
{
    float2 verts[ 3 ] = { float2( -1.0, -3.0 ),
                          float2( -1.0,  1.0 ),
                          float2(  3.0,  1.0 ) };
    float2 uvs  [ 3 ] = { float2( 0.0, 2.0 ),
                          float2( 0.0, 0.0 ),
                          float2( 2.0, 0.0 ) };
    VertexOut out;
    out.position = float4( verts[ vid ], 0.0, 1.0 );
    out.uv       = uvs[ vid ];
    return out;
}

fragment float4 fs_main( VertexOut in [[stage_in]],
                         texture2d< float > _aaa_tex_0 [[texture(0)]],
                         texture2d< float > _aaa_tex_1 [[texture(1)]],
                         texture2d< float > _aaa_tex_2 [[texture(2)]],
                         texture2d< float > _aaa_tex_3 [[texture(3)]],
                         sampler _aaa_samp [[sampler(0)]],
                         constant AaaFuFloats& _aaa_floats [[buffer(0)]] )
{
    float4 _aaa_fragout = float4( 0.0 );
    float4 color;
    color  = _aaa_floats.values[0] * _aaa_tex_0.sample(_aaa_samp, in.uv);
    color += _aaa_floats.values[1] * _aaa_tex_1.sample(_aaa_samp, in.uv);
    _aaa_fragout = color;
    return _aaa_fragout;
}
)MSL";

TEST( ShaderMslPort, PsMaa4tex_ToolGeneratedMslBuildsProgram )
{
    GOL::MetalBackend backend;
    ASSERT_TRUE( backend.init() );

    GOL::ProgramId prog = backend.create_program_msl(
        kPsMaa4texMsl, "vs_main", "fs_main" );

    ASSERT_NE( prog, GOL::kInvalidProgramId )
        << "MetalBackend rejected tool-generated MSL for ps_Maa_4tex : "
        << backend.get_last_error();

    backend.delete_program( prog );
}
